server {
  bind_address = "0.0.0.0"
  bind_port = "8081"
  trust_domain = "custodian.local"
  data_dir = "/run/spire/data"
  socket_path = "/run/spire/data/api.sock"
  log_level = "INFO"
  ca_subject {
    country = ["US"]
    organization = ["Custodian"]
    common_name = "custodian.local"
  }
}

plugins {
  DataStore "sql" {
    plugin_data {
      database_type = "sqlite3"
      connection_string = "/run/spire/data/datastore.sqlite3"
    }
  }

  NodeAttestor "join_token" {
    plugin_data {}
  }

  KeyManager "disk" {
    plugin_data {
      keys_path = "/run/spire/data/keys.json"
    }
  }
}
